document.addEventListener("DOMContentLoaded",
    function(){
        //Rendernskills
        renderSkills();
        initModal();
        initContactValidation();
        initThemeToggle();
        projectSearch();
    }
)